application: petrolgate
version: 1
runtime: python27
api_version: 1
threadsafe: true
skip_files:
- (^node_modules/.*)
- (^.git/.*)

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: MySQLdb
  version: "latest"

handlers:
- url: /static/images/(.*)
  static_files: static/images/\1
  expiration: "1d"
  upload: static/images/(.*)
  secure: always

- url: /login
  script: Controllers.login.app
  secure: always

- url: /logout
  script: Controllers.login.app
  secure: always

- url: /register/(.*)
  script: Controllers.register.app
  secure: always

- url: /(.*)
  script: main.app
  secure: always

